const vocabMix = [
  { eng: "to live", taj: ["зиндагӣ кардан"], level: 3 },
  { eng: "love", taj: ["муҳаббат"], level: 4 },
  { eng: "patience", taj: ["пурсабрӣ"], level: 4 },
  { eng: "camel", taj: ["шутур"], level: 3 },
  { eng: "alive", taj: ["зинда"], level: 3 },
  {
    eng: "to bury",
    taj: ["дафн кардан", "ба хок супоридан", "гӯрондан"],
    level: 3
  },
  { eng: "joy", taj: ["шодмонӣ", "шодӣ"], level: 4 },
  { eng: "life", taj: ["ҳаёт"], level: 5 },
  { eng: "wisdom", taj: ["ҳикмат", "хирад"], level: 5 },
  { eng: "to lie", taj: ["дурӯғ кардан", "дурӯғ гуфтан"], level: 4 },
  { eng: "peace", taj: ["осоиштагӣ", "оромӣ"], level: 5 },
  { eng: "power", taj: ["қувват"], level: 2 },
  { eng: "to command", taj: ["фармудан"], level: 5 },
  { eng: "death", taj: ["мамот", "марг"], level: 1 },
  { eng: "to deny", taj: ["инкор кардан"], level: 7 },
  { eng: "world", taj: ["ҷаҳон"], level: 1 },
  { eng: "good (adjective)", taj: ["хуб", "нек", "нағз"], level: 1 },
  { eng: "freedom", taj: ["озодӣ"], level: 7 },
  { eng: "to give birth", taj: ["зоидан", "таваллуд кардан"], level: 3 },
  { eng: "to be born", taj: ["таваллуд шудан"], level: 5 },
  { eng: "tomb", taj: ["қабр"], level: 2 },
  { eng: "boy", taj: ["писар", "бача"], level: 1 },
  { eng: "girl", taj: ["духтар"], level: 1 },
  { eng: "perfect", taj: ["комил", "беайб"], level: 4 },
  { eng: "gentleness", taj: ["фурӯтанӣ", "нармдилӣ"], level: 4 },
  { eng: "mercy", taj: ["марҳамат", "раҳм"], level: 5 },
  { eng: "bad (adjective)", taj: ["бад", "ганда"], level: 1 },
  { eng: "dead", taj: ["мурда"], level: 3 },
  { eng: "to die", taj: ["мурдан"], level: 1 },
  { eng: "hope", taj: ["умед"], level: 1 },
  { eng: "pure", taj: ["пок"], level: 1 },
  { eng: "kindness", taj: ["меҳрубонӣ"], level: 4 },
  { eng: "debt", taj: ["қарз"], level: 3 },
  { eng: "promise", taj: ["ваъда"], level: 2 },
  { eng: "cat", taj: ["пишак", "гурба"], level: 2 },
  { eng: "dog", taj: ["саг"], level: 3 },
  { eng: "earth", taj: ["замин"], level: 2 },
  { eng: "sky", taj: ["осмон"], level: 2 },
  { eng: "sea", taj: ["баҳр"], level: 3 },
  { eng: "baby", taj: ["нинича"], level: 3 },
  { eng: "test1", taj: ["test1", "test"], level: 6 },
  { eng: "test2", taj: ["test2", "test"], level: 6 },
  { eng: "test3", taj: ["test3", "test"], level: 6 },
  { eng: "test4", taj: ["test4", "test"], level: 6 },
  { eng: "test5", taj: ["test5", "test"], level: 6 },
  { eng: "test6", taj: ["test6", "test"], level: 6 },
  { eng: "test7", taj: ["test7", "test"], level: 6 },
  { eng: "test8", taj: ["test8", "test"], level: 6 }
];

export default vocabMix;
